# Generated by Django 4.0.2 on 2022-02-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cv_image/'),
        ),
    ]
